import Hsfnlean
-- Pilot (2026-07-10)
#print axioms HSFN.Addr.card_eq_sum
#print axioms HSFN.Addr.card_closed
#print axioms HSFN.Addr.card_tier
#print axioms HSFN.degree_eq
#print axioms HSFN.dval_lipschitz
#print axioms HSFN.exists_step
#print axioms HSFN.dist_eq_dval
#print axioms HSFN.graph_connected
#print axioms HSFN.dist_le_diam
#print axioms HSFN.exists_dist_eq_diam
-- Phase 2 (2026-09-05): links, update order, family monotonicity, cliques, cut vertices
#print axioms HSFN.two_mul_card_edges
#print axioms HSFN.sum_degree_eq
#print axioms HSFN.card_edges_closed
#print axioms HSFN.mem_dfsW_iff
#print axioms HSFN.dfsW_nodup
#print axioms HSFN.mem_dfsList
#print axioms HSFN.dfsList_nodup
#print axioms HSFN.dfsList_length
#print axioms HSFN.dfsList_formPerm_isCycle
#print axioms HSFN.dfsList_formPerm_support
#print axioms HSFN.castAddr_injective
#print axioms HSFN.castAddr_castAddr
#print axioms HSFN.adj_castAddr_iff
#print axioms HSFN.dval_castAddr
#print axioms HSFN.dist_castAddr
#print axioms HSFN.isMark_castAddr_iff
#print axioms HSFN.isClique_anchored
#print axioms HSFN.isClique_tier1
#print axioms HSFN.card_anchored
#print axioms HSFN.card_tier1
#print axioms HSFN.isClique_subset
#print axioms HSFN.card_le_of_isClique
#print axioms HSFN.cliqueNum_eq
#print axioms HSFN.card_desc
#print axioms HSFN.desc_nonempty
#print axioms HSFN.adj_desc_boundary
#print axioms HSFN.exists_outside
#print axioms HSFN.not_reachable_of_desc
