import Hsfnlean
-- Pilot (2026-07-10)
#print axioms HSFN.Addr.card_eq_sum
#print axioms HSFN.Addr.card_closed
#print axioms HSFN.Addr.card_tier
#print axioms HSFN.degree_eq
#print axioms HSFN.dval_lipschitz
#print axioms HSFN.exists_step
#print axioms HSFN.dist_eq_dval
#print axioms HSFN.graph_connected
#print axioms HSFN.dist_le_diam
#print axioms HSFN.exists_dist_eq_diam
-- Phase 2 (2026-09-05): links, update order, family monotonicity, cliques, cut vertices
#print axioms HSFN.two_mul_card_edges
#print axioms HSFN.sum_degree_eq
#print axioms HSFN.card_edges_closed
#print axioms HSFN.mem_dfsW_iff
#print axioms HSFN.dfsW_nodup
#print axioms HSFN.mem_dfsList
#print axioms HSFN.dfsList_nodup
#print axioms HSFN.dfsList_length
#print axioms HSFN.dfsList_formPerm_isCycle
#print axioms HSFN.dfsList_formPerm_support
#print axioms HSFN.castAddr_injective
#print axioms HSFN.castAddr_castAddr
#print axioms HSFN.adj_castAddr_iff
#print axioms HSFN.dval_castAddr
#print axioms HSFN.dist_castAddr
#print axioms HSFN.isMark_castAddr_iff
#print axioms HSFN.isClique_anchored
#print axioms HSFN.isClique_tier1
#print axioms HSFN.card_anchored
#print axioms HSFN.card_tier1
#print axioms HSFN.isClique_subset
#print axioms HSFN.card_le_of_isClique
#print axioms HSFN.cliqueNum_eq
#print axioms HSFN.card_desc
#print axioms HSFN.desc_nonempty
#print axioms HSFN.adj_desc_boundary
#print axioms HSFN.exists_outside
#print axioms HSFN.not_reachable_of_desc
-- Phase 3 (2026-09-05): threshold theory, relabelings, greedy routing, dense counts, maximal cliques, tree embedding
#print axioms HSFN.binTail_le_one
#print axioms HSFN.one_sub_binTail_le
#print axioms HSFN.two_mul_lt_one_of_belowQ0
#print axioms HSFN.f_mem_Icc
#print axioms HSFN.iterate_mem_Icc
#print axioms HSFN.iterate_le_two_mul
#print axioms HSFN.lt_q0_iff
#print axioms HSFN.lt_f_of_large_q
#print axioms HSFN.root_bound
#print axioms HSFN.binTail_antitoneOn
#print axioms HSFN.f_monotoneOn
#print axioms HSFN.iterate_mono
#print axioms HSFN.relabel_injective
#print axioms HSFN.relabelAddr_bijective
#print axioms HSFN.adj_relabelAddr_iff
#print axioms HSFN.isMark_relabelAddr_iff
#print axioms HSFN.exists_mark_moved
#print axioms HSFN.greedyStep_adj
#print axioms HSFN.dval_greedyStep
#print axioms HSFN.greedyW_iterate
#print axioms HSFN.greedyW_iterate_ne
#print axioms HSFN.Dense.V_closed
#print axioms HSFN.Dense.N_dvd_V
#print axioms HSFN.Dense.V_bounds
#print axioms HSFN.Dense.level_count
#print axioms HSFN.Dense.message_proxy
#print axioms HSFN.isMaxClique_anchored
#print axioms HSFN.isMaxClique_tier1
#print axioms HSFN.isMaxClique_iff
#print axioms HSFN.treeEmbedAddr_injective
#print axioms HSFN.treeEmbedAddr_adj
