import Hsfnlean
-- Pilot (2026-07-10)
#print axioms HSFN.Addr.card_eq_sum
#print axioms HSFN.Addr.card_closed
#print axioms HSFN.Addr.card_tier
#print axioms HSFN.degree_eq
#print axioms HSFN.dval_lipschitz
#print axioms HSFN.exists_step
#print axioms HSFN.dist_eq_dval
#print axioms HSFN.graph_connected
#print axioms HSFN.dist_le_diam
#print axioms HSFN.exists_dist_eq_diam
-- Phase 2 (2026-09-05): links, update order, family monotonicity, cliques, cut vertices
#print axioms HSFN.two_mul_card_edges
#print axioms HSFN.sum_degree_eq
#print axioms HSFN.card_edges_closed
#print axioms HSFN.mem_dfsW_iff
#print axioms HSFN.dfsW_nodup
#print axioms HSFN.mem_dfsList
#print axioms HSFN.dfsList_nodup
#print axioms HSFN.dfsList_length
#print axioms HSFN.dfsList_formPerm_isCycle
#print axioms HSFN.dfsList_formPerm_support
#print axioms HSFN.castAddr_injective
#print axioms HSFN.castAddr_castAddr
#print axioms HSFN.adj_castAddr_iff
#print axioms HSFN.dval_castAddr
#print axioms HSFN.dist_castAddr
#print axioms HSFN.isMark_castAddr_iff
#print axioms HSFN.isClique_anchored
#print axioms HSFN.isClique_tier1
#print axioms HSFN.card_anchored
#print axioms HSFN.card_tier1
#print axioms HSFN.isClique_subset
#print axioms HSFN.card_le_of_isClique
#print axioms HSFN.cliqueNum_eq
#print axioms HSFN.card_desc
#print axioms HSFN.desc_nonempty
#print axioms HSFN.adj_desc_boundary
#print axioms HSFN.exists_outside
#print axioms HSFN.not_reachable_of_desc
-- Phase 3 (2026-09-05): threshold theory, relabelings, greedy routing, dense counts, maximal cliques, tree embedding
#print axioms HSFN.binTail_le_one
#print axioms HSFN.one_sub_binTail_le
#print axioms HSFN.two_mul_lt_one_of_belowQ0
#print axioms HSFN.f_mem_Icc
#print axioms HSFN.iterate_mem_Icc
#print axioms HSFN.iterate_le_two_mul
#print axioms HSFN.lt_q0_iff
#print axioms HSFN.lt_f_of_large_q
#print axioms HSFN.root_bound
#print axioms HSFN.binTail_antitoneOn
#print axioms HSFN.f_monotoneOn
#print axioms HSFN.iterate_mono
#print axioms HSFN.relabel_injective
#print axioms HSFN.relabelAddr_bijective
#print axioms HSFN.adj_relabelAddr_iff
#print axioms HSFN.isMark_relabelAddr_iff
#print axioms HSFN.exists_mark_moved
#print axioms HSFN.greedyStep_adj
#print axioms HSFN.dval_greedyStep
#print axioms HSFN.greedyW_iterate
#print axioms HSFN.greedyW_iterate_ne
#print axioms HSFN.Dense.V_closed
#print axioms HSFN.Dense.N_dvd_V
#print axioms HSFN.Dense.V_bounds
#print axioms HSFN.Dense.level_count
#print axioms HSFN.Dense.message_proxy
#print axioms HSFN.isMaxClique_anchored
#print axioms HSFN.isMaxClique_tier1
#print axioms HSFN.isMaxClique_iff
#print axioms HSFN.treeEmbedAddr_injective
#print axioms HSFN.treeEmbedAddr_adj
-- Phase 5 (2026-09-06, ultracode sweep): 23 modules
-- Equidistance
#print axioms HSFN.Equidistance.norm_sub_of_equidistant
#print axioms HSFN.Equidistance.aux_norm_diffVec
#print axioms HSFN.Equidistance.inner_diffVec_self
#print axioms HSFN.Equidistance.inner_diffVec_ne
#print axioms HSFN.Equidistance.gram_eq
#print axioms HSFN.Equidistance.gram_quadratic
#print axioms HSFN.Equidistance.norm_sq_combination
#print axioms HSFN.Equidistance.aux_sum_sq_pos
#print axioms HSFN.Equidistance.gram_posDef
#print axioms HSFN.Equidistance.linearIndependent_diffVec
#print axioms HSFN.Equidistance.linearIndependent_diffVec_of_pos
#print axioms HSFN.Equidistance.card_le_finrank_succ
#print axioms HSFN.Equidistance.card_le_dim_succ
#print axioms HSFN.Equidistance.dimension_price_of_equality
-- Locator
#print axioms HSFN.Locator.cellField_capacity
#print axioms HSFN.Locator.tierField_capacity
#print axioms HSFN.Locator.digitField_capacity
#print axioms HSFN.Locator.locBits_eq
#print axioms HSFN.Locator.locBits_mono
#print axioms HSFN.Locator.locBits_top
#print axioms HSFN.Locator.locBits_le_locMax
#print axioms HSFN.Locator.addrBits_le_locMax
#print axioms HSFN.Locator.card_tier_le_two_pow_digits
#print axioms HSFN.Locator.locBits_example
#print axioms HSFN.Locator.pow_le_card
#print axioms HSFN.Locator.card_le_pow
#print axioms HSFN.Locator.logb_card_bounds
#print axioms HSFN.Locator.card_le_two_pow_locMax
#print axioms HSFN.Locator.locator_ratio_tendsto
#print axioms HSFN.Locator.one_le_clog_ratio
#print axioms HSFN.Locator.clog_ratio_le
#print axioms HSFN.Locator.clog_ratio_lt
#print axioms HSFN.Locator.clog_ratio_eq_one_iff
#print axioms HSFN.Locator.clog_ratio_bound_tendsto
-- TierLocator
#print axioms HSFN.TierLocator.tierBits_eq
#print axioms HSFN.TierLocator.countingBound_bounds
#print axioms HSFN.TierLocator.tendsto_tierBits_div_countingBound
#print axioms HSFN.TierLocator.ratioLimit_five
#print axioms HSFN.TierLocator.ratioLimit_three
#print axioms HSFN.TierLocator.tendsto_ratio_five
#print axioms HSFN.TierLocator.tendsto_ratio_three
-- Protocol
#print axioms HSFN.Protocol.degree_eq
#print axioms HSFN.Protocol.degree_root
#print axioms HSFN.Protocol.degree_internal
#print axioms HSFN.Protocol.degree_leaf
#print axioms HSFN.Protocol.two_mul_card_edges
#print axioms HSFN.Protocol.card_nonRoot
#print axioms HSFN.Protocol.two_mul_card_edges'
#print axioms HSFN.Protocol.exists_survivor
#print axioms HSFN.Protocol.adj_same_cell
#print axioms HSFN.Protocol.adj_parent_child
#print axioms HSFN.Protocol.induce_compl_reachable
#print axioms HSFN.Protocol.card_cell
#print axioms HSFN.Protocol.leaf_cell_separated
-- SecurityRec
#print axioms HSFN.leafQ_eq
#print axioms HSFN.leafQ_mem_unit
#print axioms HSFN.levelP_top
#print axioms HSFN.levelP_step
#print axioms HSFN.levelP_unique
#print axioms HSFN.levelP_eq_foldr
#print axioms HSFN.levelP_one_eq_foldr
#print axioms HSFN.levelP_const
#print axioms HSFN.levelP_dense
#print axioms HSFN.levelP_depth_one
#print axioms HSFN.half_two_mul
#print axioms HSFN.half_succ
#print axioms HSFN.f_dense_explicit
#print axioms HSFN.f_root_explicit
#print axioms HSFN.levelP_step_dense_explicit
#print axioms HSFN.levelP_root_explicit
#print axioms HSFN.f_mono_q
#print axioms HSFN.levelP_mem_unit
#print axioms HSFN.levelP_mono_leaf
#print axioms HSFN.levelP_one_mono_leaf
#print axioms HSFN.successRate_antitone_leaf
#print axioms HSFN.levelP_hsfn
#print axioms HSFN.levelP_dense_witness
-- DenseUpdate
#print axioms HSFN.DenseUpdate.aux_valid_prefix
#print axioms HSFN.DenseUpdate.DNode
#print axioms HSFN.DenseUpdate.toSigma_injective
#print axioms HSFN.DenseUpdate.dfsD_eq_childList
#print axioms HSFN.DenseUpdate.valid_append_iff
#print axioms HSFN.DenseUpdate.veto_iff_eq_last
#print axioms HSFN.DenseUpdate.existsUnique_veto
#print axioms HSFN.DenseUpdate.mem_childRaw_iff
#print axioms HSFN.DenseUpdate.childRaw_nodup
#print axioms HSFN.DenseUpdate.childList_of_last_tier
#print axioms HSFN.DenseUpdate.length_childList_root
#print axioms HSFN.DenseUpdate.length_childList_of_ne_nil
#print axioms HSFN.DenseUpdate.aux_childRaw_append
#print axioms HSFN.DenseUpdate.aux_mem_dfsD_prefix
#print axioms HSFN.DenseUpdate.mem_dfsD_iff
#print axioms HSFN.DenseUpdate.dfsD_nodup
#print axioms HSFN.DenseUpdate.toDNode_dfsD_isSome
#print axioms HSFN.DenseUpdate.mem_dfsList
#print axioms HSFN.DenseUpdate.dfsList_nodup
#print axioms HSFN.DenseUpdate.dfsList_length
#print axioms HSFN.DenseUpdate.le_card_DNode
#print axioms HSFN.DenseUpdate.dfsList_formPerm_isCycle
#print axioms HSFN.DenseUpdate.dfsList_formPerm_support
-- ClawFree
#print axioms HSFN.mem_birthClique_iff
#print axioms HSFN.self_mem_birthClique
#print axioms HSFN.sibF_subset_birthClique
#print axioms HSFN.parF_subset_birthClique
#print axioms HSFN.isClique_birthClique
#print axioms HSFN.isClique_sibF
#print axioms HSFN.isClique_chiF
#print axioms HSFN.neighborSet_subset_birthClique_union_chiF
#print axioms HSFN.neighborFinset_subset_birthClique_union_chiF
#print axioms HSFN.neighborSet_subset_sibF_union_chiF
#print axioms HSFN.clawFree
#print axioms HSFN.card_le_two_of_isIndepSet_of_subset_neighbors
-- TreeDecomp
#print axioms HSFN.TreeDecomp.bag_eq_anchored
#print axioms HSFN.TreeDecomp.rootBag_eq_tier1
#print axioms HSFN.TreeDecomp.isClique_bag
#print axioms HSFN.TreeDecomp.isClique_rootBag
#print axioms HSFN.TreeDecomp.anchorOf_val
#print axioms HSFN.TreeDecomp.anchorOf_tier
#print axioms HSFN.TreeDecomp.mem_bag_iff
#print axioms HSFN.TreeDecomp.mem_rootBag_iff
#print axioms HSFN.TreeDecomp.mem_bag_self
#print axioms HSFN.TreeDecomp.treeParent_tier_lt
#print axioms HSFN.TreeDecomp.mem_bagAt_treeParent
#print axioms HSFN.TreeDecomp.mem_bagAt_some_self
#print axioms HSFN.TreeDecomp.mem_rootBag_of_tier_one
#print axioms HSFN.TreeDecomp.mem_bag_anchorOf
#print axioms HSFN.TreeDecomp.cover
#print axioms HSFN.TreeDecomp.edge_cover_sib
#print axioms HSFN.TreeDecomp.edge_cover_sib_tier_one
#print axioms HSFN.TreeDecomp.edge_cover_par
#print axioms HSFN.TreeDecomp.edge_cover
#print axioms HSFN.TreeDecomp.edge_cover_idx
#print axioms HSFN.TreeDecomp.card_bag_le
#print axioms HSFN.TreeDecomp.card_bag_of_lt
#print axioms HSFN.TreeDecomp.card_bag_of_leaf
#print axioms HSFN.TreeDecomp.card_rootBag
#print axioms HSFN.TreeDecomp.card_bagAt_le
#print axioms HSFN.TreeDecomp.exists_card_bag_eq
#print axioms HSFN.TreeDecomp.card_bagAt_le_of_m_one
#print axioms HSFN.TreeDecomp.coherence
#print axioms HSFN.TreeDecomp.eq_anchorOf_of_mem_bag
#print axioms HSFN.TreeDecomp.eq_self_of_mem_bag_of_tier_one
#print axioms HSFN.TreeDecomp.coherence_rootBag
#print axioms HSFN.TreeDecomp.coherence_idx
#print axioms HSFN.TreeDecomp.bag_inter_parent
#print axioms HSFN.TreeDecomp.rootBag_inter_bag
#print axioms HSFN.TreeDecomp.tw_le
-- AvgDegree
#print axioms HSFN.two_mul_card_edges_mul_pow
#print axioms HSFN.avgDeg_eq
#print axioms HSFN.avgDeg_strictMono
#print axioms HSFN.avgDeg_mono
#print axioms HSFN.tendsto_avgDeg
-- PartialFill
#print axioms HSFN.PartialFill.VII_eq_card
#print axioms HSFN.PartialFill.lowerCells_closed
#print axioms HSFN.PartialFill.aux_mix_sub_sq
#print axioms HSFN.PartialFill.mix_ge_sq
#print axioms HSFN.PartialFill.mix_eq_sq_iff
#print axioms HSFN.PartialFill.mix_natCast
#print axioms HSFN.PartialFill.aux_VII_succ
#print axioms HSFN.PartialFill.aux_cells_total
#print axioms HSFN.PartialFill.kbar_full
#print axioms HSFN.PartialFill.CII_full
#print axioms HSFN.PartialFill.N_dvd_VII
#print axioms HSFN.PartialFill.CII_full_eq_dense_proxy
#print axioms HSFN.PartialFill.full_population_form_independent
#print axioms HSFN.PartialFill.minimalDepth_witness
-- IFS
#print axioms HSFN.IFS.fBary_apply
#print axioms HSFN.IFS.vtx_mem_simplex
#print axioms HSFN.IFS.fBary_fixed
#print axioms HSFN.IFS.aux_sum_fBary
#print axioms HSFN.IFS.fBary_mem_simplex
#print axioms HSFN.IFS.half_le_fBary
#print axioms HSFN.IFS.fBary_image_simplex
#print axioms HSFN.IFS.aux_fBary_sub
#print axioms HSFN.IFS.nrm1_fBary_sub
#print axioms HSFN.IFS.norm_fBary_sub
#print axioms HSFN.IFS.fBary_lipschitz
#print axioms HSFN.IFS.simplexInt_subset_simplex
#print axioms HSFN.IFS.center_mem_simplexInt
#print axioms HSFN.IFS.simplexInt_relatively_open
#print axioms HSFN.IFS.not_half_lt_of_ne
#print axioms HSFN.IFS.fBary_image_interior_subset
#print axioms HSFN.IFS.half_lt_fBary_of_mem_interior
#print axioms HSFN.IFS.fBary_image_interior_disjoint
#print axioms HSFN.IFS.moran_iff
#print axioms HSFN.IFS.moran_moranDim
#print axioms HSFN.IFS.moranDim_eq
-- RunningExample
#print axioms HSFN.RunningExample.tier_a4
#print axioms HSFN.RunningExample.tier_a42
#print axioms HSFN.RunningExample.tier_a43
#print axioms HSFN.RunningExample.tier_a420
#print axioms HSFN.RunningExample.tier_a431
#print axioms HSFN.RunningExample.card_addr
#print axioms HSFN.RunningExample.card_addr_sum
#print axioms HSFN.RunningExample.card_tier_one
#print axioms HSFN.RunningExample.card_tier_two
#print axioms HSFN.RunningExample.card_tier_three
#print axioms HSFN.RunningExample.card_mem_cells
#print axioms HSFN.RunningExample.card_cells
#print axioms HSFN.RunningExample.cells_times_size
#print axioms HSFN.RunningExample.card_addr_div
#print axioms HSFN.RunningExample.cell_count_sum
#print axioms HSFN.RunningExample.dist_le_five
#print axioms HSFN.RunningExample.exists_dist_eq_five
#print axioms HSFN.RunningExample.diam_eq_five
#print axioms HSFN.RunningExample.lcp_a000_a444
#print axioms HSFN.RunningExample.not_prefixComp_a000_a444
#print axioms HSFN.RunningExample.dist_a000_a444
#print axioms HSFN.RunningExample.lcp_a420_a431
#print axioms HSFN.RunningExample.not_prefixComp_a420_a431
#print axioms HSFN.RunningExample.dval_a420_a431
#print axioms HSFN.RunningExample.dist_a420_a431
#print axioms HSFN.RunningExample.route_a420_a431
#print axioms HSFN.RunningExample.tree_route_a420_a431
#print axioms HSFN.RunningExample.degree_of_tier_one
#print axioms HSFN.RunningExample.degree_of_tier_two
#print axioms HSFN.RunningExample.degree_of_tier_three
#print axioms HSFN.RunningExample.degree_a4
#print axioms HSFN.RunningExample.degree_a42
#print axioms HSFN.RunningExample.degree_a420
#print axioms HSFN.RunningExample.clog_five
#print axioms HSFN.RunningExample.clog_three
#print axioms HSFN.RunningExample.locatorBits_a431
#print axioms HSFN.RunningExample.locatorBits_le
-- RelabelGroup
#print axioms HSFN.relabel_relabelOne
#print axioms HSFN.relabelAddr_relabelOne
#print axioms HSFN.relabelAddr_relabelOne_eq_id
#print axioms HSFN.relabel_comp
#print axioms HSFN.relabelAddr_comp
#print axioms HSFN.relabelAddr_comp_eq
#print axioms HSFN.relabelComp_assoc
#print axioms HSFN.relabelComp_one_right
#print axioms HSFN.relabelComp_one_left
#print axioms HSFN.exists_relabelComp_inv
#print axioms HSFN.relabelPerm_apply
#print axioms HSFN.relabelPerm_one
#print axioms HSFN.relabelPerm_mul
#print axioms HSFN.exists_relabelPerm_inv
#print axioms HSFN.mem_relabelSubgroup_iff
#print axioms HSFN.adj_relabelPerm_iff
#print axioms HSFN.relabelIso_apply
#print axioms HSFN.relabelIso_comp
#print axioms HSFN.relabelIso_relabelOne
#print axioms HSFN.adj_iff_of_mem_relabelSubgroup
#print axioms HSFN.fixesZero_iff_mem_stabilizer
#print axioms HSFN.nonempty_stabilizer_mulEquiv
#print axioms HSFN.fixesZero_relabelOne
#print axioms HSFN.fixesZero_relabelComp
#print axioms HSFN.exists_fixesZero_inv
#print axioms HSFN.markedRelabelSubgroup_le_relabelSubgroup
#print axioms HSFN.isMark_iff_of_mem_markedRelabelSubgroup
#print axioms HSFN.fixesZero_of_mapsTo_isMark
#print axioms HSFN.mapsTo_isMark_relabelAddr_iff_fixesZero
#print axioms HSFN.isMark_relabelAddr_iff_iff_fixesZero
#print axioms HSFN.mem_markedRelabelSubgroup_iff
#print axioms HSFN.exists_mem_relabelSubgroup_moving_mark
#print axioms HSFN.markedRelabelSubgroup_lt_relabelSubgroup
-- Delay
#print axioms HSFN.Delay.card_pow_bounds
#print axioms HSFN.Delay.card_pow_bounds_real
#print axioms HSFN.Delay.depth_eq_logb
#print axioms HSFN.Delay.delay_eq_logb
#print axioms HSFN.Delay.dense_pow_bounds
#print axioms HSFN.Delay.dense_depth_eq_logb
#print axioms HSFN.Delay.dense_delay_eq_logb
#print axioms HSFN.Delay.depth_le_of_card_le
#print axioms HSFN.Delay.delay_le_of_card_le
-- Chordal
#print axioms HSFN.chordal_sib_or_parent_of_adj_of_maxTier
#print axioms HSFN.chordal_adj_of_sib_or_parent
#print axioms HSFN.chordal
#print axioms HSFN.exists_cycle_length_four
#print axioms HSFN.chordal_applies
-- EdgeCut
#print axioms HSFN.Calc.mem_movedSlots
#print axioms HSFN.Calc.mem_movedCells
#print axioms HSFN.Calc.mem_sibCells
#print axioms HSFN.Calc.sib_stays_moved
#print axioms HSFN.Calc.child_stays_moved
#print axioms HSFN.Calc.crossing_forces_uplink
#print axioms HSFN.Calc.cellW_subset_movedSlots
#print axioms HSFN.Calc.card_uplinks_into_anchor
#print axioms HSFN.Calc.boundaryPairs_eq
#print axioms HSFN.Calc.card_boundaryPairs
#print axioms HSFN.Calc.movedSlots_graft
#print axioms HSFN.Calc.boundaryPairs_graft_eq
#print axioms HSFN.Calc.card_boundaryPairs_graft
#print axioms HSFN.Calc.cellCutPairs_eq
#print axioms HSFN.Calc.card_cellCutPairs
#print axioms HSFN.Calc.cellCutPairs_graft_eq
#print axioms HSFN.Calc.card_cellCutPairs_graft
#print axioms HSFN.Calc.cellsOutside_graft
#print axioms HSFN.Calc.adjCell_outside_graft
#print axioms HSFN.Calc.adjCell_moved_graft
#print axioms HSFN.Calc.movedCells_graft
#print axioms HSFN.Calc.substFalse_inj_on_movedCells
#print axioms HSFN.Calc.substTrue_inj_on_movedSlots
#print axioms HSFN.Calc.card_movedCells_graft
#print axioms HSFN.Calc.card_movedSlots_graft
-- GraftIso
#print axioms HSFN.Calc.subst_append_of_ne_nil
#print axioms HSFN.Calc.subst_self_false
#print axioms HSFN.Calc.subst_self_true
#print axioms HSFN.Calc.subst_drop_eq
#print axioms HSFN.Calc.subst_mem_cone
#print axioms HSFN.Calc.subst_length_eq
#print axioms HSFN.Calc.mem_markedSet_iff
#print axioms HSFN.Calc.markedSet_subset_Sl
#print axioms HSFN.Calc.isMarkW_append_iff
#print axioms HSFN.Calc.isMarkW_subst_iff
#print axioms HSFN.Calc.graft_mem_markedSet_iff
#print axioms HSFN.Calc.graft_markedSet_cone
#print axioms HSFN.Calc.mem_movedSlots_iff
#print axioms HSFN.Calc.movedSlots_nonempty
#print axioms HSFN.Calc.graft_mapsTo_movedSlots
#print axioms HSFN.Calc.graft_injOn_movedSlots
#print axioms HSFN.Calc.graft_surjOn_movedSlots
#print axioms HSFN.Calc.graft_bijOn_movedSlots
#print axioms HSFN.Calc.graft_adjW_iff
#print axioms HSFN.Calc.graft_adjW_preserve
#print axioms HSFN.Calc.graft_adjW_reflect
#print axioms HSFN.Calc.graft_iso
#print axioms HSFN.Calc.graft_mem_mu_iff_moved
#print axioms HSFN.Calc.graft_mem_zeta_iff_moved
#print axioms HSFN.Calc.graft_mem_mu_iff_static
#print axioms HSFN.Calc.graft_mem_zeta_iff_static
#print axioms HSFN.Calc.graft_anchor_stays
#print axioms HSFN.Calc.graft_anchor_not_zeta
#print axioms HSFN.Calc.graft_mem_D_iff_moved
#print axioms HSFN.Calc.graft_mem_D_iff_static
#print axioms HSFN.Calc.graft_hypotheses_satisfiable
-- KpiAffine
#print axioms HSFN.Kpi.card_cellW
#print axioms HSFN.Kpi.cellW_disjoint
#print axioms HSFN.Kpi.sum_tierCells
#print axioms HSFN.Kpi.sum_M0
#print axioms HSFN.Kpi.M1_o
#print axioms HSFN.Kpi.card_Sl
#print axioms HSFN.Kpi.card_Sl_profile
#print axioms HSFN.Kpi.card_mu_sum
#print axioms HSFN.Kpi.card_mu_profile
#print axioms HSFN.Kpi.adjPairs_eq
#print axioms HSFN.Kpi.card_sibPairs
#print axioms HSFN.Kpi.card_upPairs
#print axioms HSFN.Kpi.two_mul_L
#print axioms HSFN.Kpi.card_L
#print axioms HSFN.Kpi.card_L_profile
#print axioms HSFN.Kpi.Cfull_eq
#print axioms HSFN.Kpi.Cfull_profile
#print axioms HSFN.Kpi.Cload_hist
#print axioms HSFN.Kpi.Cload_full
#print axioms HSFN.Kpi.card_join
#print axioms HSFN.Kpi.card_leave
#print axioms HSFN.Kpi.card_spawn
#print axioms HSFN.Kpi.card_retract
#print axioms HSFN.Kpi.card_graft
#print axioms HSFN.Kpi.disable_D_mu
#print axioms HSFN.Kpi.enable_D_mu
#print axioms HSFN.Kpi.occ_join
#print axioms HSFN.Kpi.occ_leave
#print axioms HSFN.Kpi.kappa_spawn
#print axioms HSFN.Kpi.kappa_retract
#print axioms HSFN.Kpi.occ_kappa_spawn_new
#print axioms HSFN.Kpi.card_Sl_spawn
#print axioms HSFN.Kpi.card_Sl_retract
#print axioms HSFN.Kpi.graft_card_Sl
#print axioms HSFN.Kpi.graft_L
#print axioms HSFN.Kpi.graft_Cfull
-- CanonWord
#print axioms HSFN.Calc.runWord_append
#print axioms HSFN.Calc.canonical_eq_runWord
#print axioms HSFN.Calc.exists_spawnOrder
#print axioms HSFN.Calc.exists_enumerates
#print axioms HSFN.Calc.spawn_step_of_mem_target
#print axioms HSFN.Calc.runSpawns_partial
#print axioms HSFN.Calc.runSpawns_all
#print axioms HSFN.Calc.runJoins_all
#print axioms HSFN.Calc.runDisables_all
#print axioms HSFN.Calc.canonical_eq
#print axioms HSFN.Calc.runWord_canonWord
#print axioms HSFN.Calc.exists_canonWord_run
#print axioms HSFN.Calc.reachable_seed_of_wf
#print axioms HSFN.Calc.wf_runGen
#print axioms HSFN.Calc.wf_runWord
#print axioms HSFN.Calc.reachable_wf
#print axioms HSFN.Calc.reachable_seed_wf
#print axioms HSFN.Calc.reachable_seed_iff
#print axioms HSFN.Calc.canonWord_normal_form
#print axioms HSFN.Calc.reachable_of_wf
-- Commute
#print axioms HSFN.Calc.fpDisjoint_symm
#print axioms HSFN.Calc.book_comm
#print axioms HSFN.Calc.wfp_sound
#print axioms HSFN.Calc.wfp_graft_leave_disjoint
#print axioms HSFN.Calc.fp_graft_leave_not_disjoint
#print axioms HSFN.Calc.ce_wf
#print axioms HSFN.Calc.book_comm_witness
#print axioms HSFN.Calc.ce_graft_defined
#print axioms HSFN.Calc.ce_leave_defined
#print axioms HSFN.Calc.ce_leave_then_graft
#print axioms HSFN.Calc.ce_graft_then_leave
#print axioms HSFN.Calc.ce_noncommute
#print axioms HSFN.Calc.write_footprint_criterion_unsound
-- RelExact
#print axioms HSFN.RelExact.quorum_eq_ceil
#print axioms HSFN.RelExact.quorum_three
#print axioms HSFN.RelExact.quorum_four
#print axioms HSFN.RelExact.pbGE_eq_pbGEsub
#print axioms HSFN.RelExact.pbGE_replicate
#print axioms HSFN.RelExact.mem_childList
#print axioms HSFN.RelExact.childCount_le
#print axioms HSFN.RelExact.pFailW_fuel_stable
#print axioms HSFN.RelExact.pFailW_of_childList_nil
#print axioms HSFN.RelExact.pFailW_of_homogeneous
#print axioms HSFN.RelExact.step_heavy
#print axioms HSFN.RelExact.step_branch_conc
#print axioms HSFN.RelExact.sum_patWeight
#print axioms HSFN.RelExact.exact_recursion
#print axioms HSFN.RelExact.faultyB_fuel_stable
#print axioms HSFN.RelExact.faultyB_seed_stable
#print axioms HSFN.RelExact.tierCount_eq_card_profile
#print axioms HSFN.RelExact.xS_wf
#print axioms HSFN.RelExact.xC_wf
#print axioms HSFN.RelExact.xS_full
#print axioms HSFN.RelExact.xC_full
#print axioms HSFN.RelExact.card_Dspread
#print axioms HSFN.RelExact.card_Dconc
#print axioms HSFN.RelExact.pFail_heavy
#print axioms HSFN.RelExact.pFail_light
#print axioms HSFN.RelExact.pFail_branch_spread
#print axioms HSFN.RelExact.pFail_branch_conc_heavy
#print axioms HSFN.RelExact.pFail_branch_conc_light
#print axioms HSFN.RelExact.Rrec_spread
#print axioms HSFN.RelExact.Rrec_conc
#print axioms HSFN.RelExact.Rrec_spread_round
#print axioms HSFN.RelExact.Rrec_conc_round
#print axioms HSFN.RelExact.Rrec_ne
#print axioms HSFN.RelExact.Rrec_conc_lt_spread
#print axioms HSFN.RelExact.Rel_spread
#print axioms HSFN.RelExact.Rel_conc
#print axioms HSFN.RelExact.Rel_ne
#print axioms HSFN.RelExact.Rel_conc_lt_spread
#print axioms HSFN.RelExact.tierCount_spread
#print axioms HSFN.RelExact.tierCount_conc
#print axioms HSFN.RelExact.profile_spread_one
#print axioms HSFN.RelExact.profile_spread_two
#print axioms HSFN.RelExact.profile_conc_two
#print axioms HSFN.RelExact.profile_eq
#print axioms HSFN.RelExact.occProfile_eq
#print axioms HSFN.RelExact.occ_eq
#print axioms HSFN.RelExact.profile_blind
#print axioms HSFN.RelExact.no_profile_formula
#print axioms HSFN.RelExact.no_affine_profile_formula
#print axioms HSFN.RelExact.no_affine_tier_formula
-- Derived
#print axioms HSFN.Calc.ne_nil_of_swapIncomp
#print axioms HSFN.Calc.swapW_append_left
#print axioms HSFN.Calc.swapW_append_right
#print axioms HSFN.Calc.swapW
#print axioms HSFN.Calc.swapW
#print axioms HSFN.Calc.swapW
#print axioms HSFN.Calc.swapW
#print axioms HSFN.Calc.swapW_of_not_prefix
#print axioms HSFN.Calc.swapW
#print axioms HSFN.Calc.swapW_append_staging
#print axioms HSFN.Calc.swapW_involutive
#print axioms HSFN.Calc.swapW
#print axioms HSFN.Calc.swap_three_grafts
#print axioms HSFN.Calc.swap_two_grafts
#print axioms HSFN.Calc.swap_cone_exchange
#print axioms HSFN.Calc.swap_staging_cone_empty
#print axioms HSFN.Calc.swapWitness_wf
#print axioms HSFN.Calc.swapWitness_defined
#print axioms HSFN.Calc.swapWitness2_wf
#print axioms HSFN.Calc.swapWitness2_exchange
-- Spacetime
#print axioms HSFN.Calc.coord_fst
#print axioms HSFN.Calc.coord_snd
#print axioms HSFN.Calc.transport_height_of_graft
#print axioms HSFN.Calc.transport_height_of_graft_root
#print axioms HSFN.Calc.transport_height_of_graft_outside
#print axioms HSFN.Calc.join_deployed_eq
#print axioms HSFN.Calc.leave_deployed_eq
#print axioms HSFN.Calc.disable_deployed_eq
#print axioms HSFN.Calc.enable_deployed_eq
#print axioms HSFN.Calc.spawn_deployed_eq
#print axioms HSFN.Calc.retract_deployed_eq
#print axioms HSFN.Calc.graft_root_not_deployed
#print axioms HSFN.Calc.graft_target_deployed
#print axioms HSFN.Calc.writesNoChainState_join
#print axioms HSFN.Calc.writesNoChainState_leave
#print axioms HSFN.Calc.writesNoChainState_disable
#print axioms HSFN.Calc.writesNoChainState_enable
#print axioms HSFN.Calc.writesNoChainState_spawn
#print axioms HSFN.Calc.writesNoChainState_retract
#print axioms HSFN.Calc.carriesHeights_id
#print axioms HSFN.Calc.coord_injective
#print axioms HSFN.Calc.coord_injOn
#print axioms HSFN.Calc.coord_graft_equivariant
#print axioms HSFN.Calc.carriesHeights_graft
#print axioms HSFN.Calc.worldline_graft
