/-
Copyright (c) 2026 Hao Xu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Hao Xu
-/
import Mathlib

/-!
# HSFN address algebra (Lean 4 formalization, pilot)

Paper: "A Mathematical Theory of Hyper-Simplex Fractal Network" (R260409).
Scope here: addresses (Definition def:address-II), the two-clause adjacency
law (Theorem thm:adjacency-II, taken as the *definition* of the graph), and
the counting law (Theorem thm:unified-count / Proposition prop:addr-bij).
-/

namespace HSFN

/-- An address of the depth-`m` HSFN over the digit alphabet `Fin N`:
a nonempty digit word of length at most `m`. -/
def Addr (N m : ℕ) : Type :=
  { l : List (Fin N) // l ≠ [] ∧ l.length ≤ m }

namespace Addr

variable {N m : ℕ}

instance : DecidableEq (Addr N m) := inferInstanceAs (DecidableEq (Subtype _))

/-- The tier of an address is its length. -/
def tier (a : Addr N m) : ℕ := a.1.length

theorem one_le_tier (a : Addr N m) : 1 ≤ a.tier :=
  List.length_pos_of_ne_nil a.2.1

theorem tier_le (a : Addr N m) : a.tier ≤ m := a.2.2

/-- An address exists only over a nonempty alphabet. -/
theorem N_pos (a : Addr N m) : 0 < N := by
  have hne := a.2.1
  rcases hl : a.1 with - | ⟨d, rest⟩
  · exact absurd hl hne
  · exact d.pos

@[ext] theorem ext {a b : Addr N m} (h : a.1 = b.1) : a = b := Subtype.ext h

/-- Addresses are the disjoint union, over tiers `t+1` for `t < m`, of the
length-`(t+1)` digit words. -/
def equivSigma (N m : ℕ) :
    Addr N m ≃ Σ t : Fin m, List.Vector (Fin N) (t + 1) where
  toFun a :=
    ⟨⟨a.1.length - 1, by
        have h1 := List.length_pos_of_ne_nil a.2.1
        have h2 := a.2.2
        omega⟩,
      ⟨a.1, by
        show a.1.length = (a.1.length - 1) + 1
        have h1 := List.length_pos_of_ne_nil a.2.1
        omega⟩⟩
  invFun p :=
    ⟨p.2.1, by
        constructor
        · intro h
          have h2 := p.2.2
          rw [h] at h2
          simp at h2
        · have h1 := p.2.2
          have h2 := p.1.isLt
          omega⟩
  left_inv a := rfl
  right_inv := by
    rintro ⟨t, v⟩
    have hv : v.1.length = t + 1 := v.2
    refine Sigma.ext ?_ ?_
    · ext
      show v.1.length - 1 = t
      omega
    · refine (Subtype.heq_iff_coe_eq ?_).mpr rfl
      intro l
      show l.length = (v.1.length - 1) + 1 ↔ l.length = t + 1
      omega

instance : Fintype (Addr N m) := Fintype.ofEquiv _ (equivSigma N m).symm

/-- Counting law, summed form: the depth-`m` HSFN has `∑_{t=1}^{m} N^t`
addresses (Theorem thm:unified-count). -/
theorem card_eq_sum (N m : ℕ) :
    Fintype.card (Addr N m) = ∑ t ∈ Finset.range m, N ^ (t + 1) := by
  rw [Fintype.card_congr (equivSigma N m), Fintype.card_sigma]
  rw [Fin.sum_univ_eq_sum_range (fun t => Fintype.card (List.Vector (Fin N) (t + 1)))]
  refine Finset.sum_congr rfl fun t _ => ?_
  rw [card_vector, Fintype.card_fin]

/-- Counting law, closed form, subtraction-free: with `N = n + 1`,
`n · |V| + N = N^{m+1}`; equivalently `(N-1)|V| = N^{m+1} - N`,
i.e. `|V| = N (N^m - 1)/(N - 1)` (Theorem thm:unified-count). -/
theorem card_closed (n m : ℕ) :
    n * Fintype.card (Addr (n + 1) m) + (n + 1) = (n + 1) ^ (m + 1) := by
  rw [card_eq_sum]
  induction m with
  | zero => simp
  | succ k ih =>
      rw [Finset.sum_range_succ, Nat.mul_add, pow_succ]
      calc n * (∑ t ∈ Finset.range k, (n + 1) ^ (t + 1)) + n * (n + 1) ^ (k + 1) + (n + 1)
          = (n * (∑ t ∈ Finset.range k, (n + 1) ^ (t + 1)) + (n + 1)) + n * (n + 1) ^ (k + 1) := by
            ring
        _ = (n + 1) ^ (k + 1) + n * (n + 1) ^ (k + 1) := by rw [ih]
        _ = (n + 1) ^ (k + 1) * (n + 1) := by ring

/-- Per-tier bijection (Proposition prop:addr-bij): tier-`t` addresses are
exactly the length-`t` digit words, for `1 ≤ t ≤ m`. -/
def tierEquiv (N m t : ℕ) (h1 : 1 ≤ t) (h2 : t ≤ m) :
    { a : Addr N m // a.tier = t } ≃ List.Vector (Fin N) t where
  toFun a := ⟨a.1.1, a.2⟩
  invFun v :=
    ⟨⟨v.1, by
        constructor
        · intro h
          have h2 := v.2
          rw [h] at h2
          simp at h2
          omega
        · have := v.2
          omega⟩, v.2⟩
  left_inv a := rfl
  right_inv v := rfl

theorem card_tier (N m t : ℕ) (h1 : 1 ≤ t) (h2 : t ≤ m) :
    Fintype.card { a : Addr N m // a.tier = t } = N ^ t := by
  rw [Fintype.card_congr (tierEquiv N m t h1 h2), card_vector, Fintype.card_fin]

end Addr

/-! ## The two-clause adjacency law (Theorem thm:adjacency-II)

In the paper the graph is generated by spawn events and the theorem states
that its edges are exactly the pairs below; in the formalization the two
clauses *define* the graph, and the structural results are proved from them.
-/

variable {N m : ℕ}

/-- Clause (S), siblings: equal tier and equal first `t-1` digits.
At tier 1 the prefix condition is vacuous (`dropLast` of both is `[]`),
so the initial cell is the sibling clique of the virtual root. -/
def Sib (u v : Addr N m) : Prop :=
  u.1.length = v.1.length ∧ u.1.dropLast = v.1.dropLast

/-- Clause (P), parent–child, computational form: one word is the other with
one further trailing digit. -/
def Par (u v : Addr N m) : Prop :=
  (v.1.length = u.1.length + 1 ∧ v.1.dropLast = u.1) ∨
  (u.1.length = v.1.length + 1 ∧ u.1.dropLast = v.1)

instance : ∀ u v : Addr N m, Decidable (Sib u v) := fun _ _ => by
  unfold Sib; infer_instance

instance : ∀ u v : Addr N m, Decidable (Par u v) := fun _ _ => by
  unfold Par; infer_instance

theorem Sib.symm {u v : Addr N m} (h : Sib u v) : Sib v u :=
  ⟨h.1.symm, h.2.symm⟩

theorem Par.symm {u v : Addr N m} (h : Par u v) : Par v u :=
  Or.symm h

/-- Clause (P) in the paper's phrasing: one address extends the other by
exactly one digit. -/
theorem par_iff_concat (u v : Addr N m) :
    Par u v ↔ (∃ d, v.1 = u.1 ++ [d]) ∨ (∃ d, u.1 = v.1 ++ [d]) := by
  constructor
  · rintro (⟨hlen, hpre⟩ | ⟨hlen, hpre⟩)
    · left
      have hne : v.1 ≠ [] := by
        intro h; rw [h] at hlen; simp at hlen
      refine ⟨v.1.getLast hne, ?_⟩
      conv_lhs => rw [← List.dropLast_append_getLast hne]
      rw [hpre]
    · right
      have hne : u.1 ≠ [] := by
        intro h; rw [h] at hlen; simp at hlen
      refine ⟨u.1.getLast hne, ?_⟩
      conv_lhs => rw [← List.dropLast_append_getLast hne]
      rw [hpre]
  · rintro (⟨d, hd⟩ | ⟨d, hd⟩)
    · exact Or.inl ⟨by rw [hd]; simp, by rw [hd]; simp⟩
    · exact Or.inr ⟨by rw [hd]; simp, by rw [hd]; simp⟩

/-- The HSFN graph on the depth-`m` addresses: the two-clause adjacency law. -/
def graph (N m : ℕ) : SimpleGraph (Addr N m) where
  Adj u v := u ≠ v ∧ (Sib u v ∨ Par u v)
  symm := by
    constructor
    rintro u v ⟨hne, hS | hP⟩
    · exact ⟨hne.symm, Or.inl hS.symm⟩
    · exact ⟨hne.symm, Or.inr hP.symm⟩
  loopless := by
    constructor
    rintro u ⟨hne, -⟩
    exact hne rfl

instance : DecidableRel (graph N m).Adj := fun u v =>
  inferInstanceAs (Decidable (u ≠ v ∧ (Sib u v ∨ Par u v)))

/-- A sibling hop preserves the tier; a parent–child hop changes it by one:
the tier function is the layering on which the distance analysis runs. -/
theorem adj_tier {u v : Addr N m} (h : (graph N m).Adj u v) :
    u.tier = v.tier ∨ u.tier = v.tier + 1 ∨ v.tier = u.tier + 1 := by
  rcases h.2 with hS | hP
  · exact Or.inl hS.1
  · rcases hP with ⟨hlen, -⟩ | ⟨hlen, -⟩
    · exact Or.inr (Or.inr hlen)
    · exact Or.inr (Or.inl hlen)

end HSFN
